config:
  http_request_timeout: 10000
  export_directory: /home/atwine/apictl/.wso2apictl/exported
  kubernetes_mode: false
  token_type: JWT
  vcs_deletion_enabled: false
  vcs_config_file_path: ""
environments:
  dev:
    apim: https://localhost:9443
    publisher: ""
    devportal: ""
    registration: ""
    admin: ""
    token: https://localhost:8243/token
  prod:
    apim: https://localhost:9444
    publisher: ""
    devportal: ""
    registration: ""
    admin: ""
    token: https://localhost:8244/token
